### ISSUE TITLE
Get alerts call error status code 204

### ISSUE THREAD

**Issue by cob94440** [Jezza34000/home-assistant-veolia#4]
Bonjour,
J'ai l'erreur citée en objet avec l'utilisation du plugin.
 avec également dans les journaux :
```
Enregistreur: VeoliaAPI
Source: custom_components/veolia/coordinator.py:55
intégration: Veolia ([documentation](https://github.com/Jezza34000/home-assistant-veolia), [problèmes](https://github.com/Jezza34000/home-assistant-veolia/issues))
S'est produit pour la première fois: 14:11:57 (2 occurrences)
Dernier enregistrement: 14:13:02
No access token or token expired
```
Mon compte se connecte bien sur le site web de veolia. en revanche j'ai un compteur qui est relevé deux fois par ans automatiquement et non en temps réel.
Est ce la problème?
Merci par avance

**Comment by Jezza34000** [comment]
Hello,
Peux-tu suivre la procédure cité en bas dans le readme pour activer la journalisation en debug.
Je ne comprends pas la problématique avec les informations données.
La relève biannuel n'est pas censé poser problème.

**Comment by Patrick44fr** [comment]
Bonjour j'obtiens la meme erreur 204 voici mes logs:
`  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.
2024-11-20 09:18:04.796 DEBUG (MainThread) [custom_components.veolia] Finished fetching veolia data in 9.811 seconds (success: False)
2024-11-20 09:18:04.797 WARNING (MainThread) [homeassistant.config_entries] Config entry 'plejalle@free.fr' for veolia integration could not authenticate: call to= mensualisation/plan failed with http status= 204
2024-11-20 09:18:04.821 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/veolia/coordinator.py", line 55, in _async_update_data
    await self.client_api.fetch_all_data(now.year, now.month)
  File "/usr/local/lib/python3.12/site-packages/veolia_api/veolia_api.py", line 502, in fetch_all_data
    self.account_data.billing_plan = await self.get_mensualisation_plan()
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/veolia_api/veolia_api.py", line 484, in get_mensualisation_plan
    raise VeoliaAPIGetDataError(
veolia_api.exceptions.VeoliaAPIGetDataError: call to= mensualisation/plan failed with http status= 204

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/veolia/__init__.py", line 37, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 309, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/veolia/coordinator.py", line 58, in _async_update_data
    raise ConfigEntryAuthFailed(exception) from exception
homeassistant.exceptions.ConfigEntryAuthFailed: call to= mensualisation/plan failed with http status= 204

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1088, in _async_init_reauth
    result = await hass.config_entries.flow.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1301, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1336, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)`

j'espère que cela va aider .
merci pour le travail accompli

**Comment by Patrick44fr** [comment]
en complément une copie de l'intégration;
![image](https://github.com/user-attachments/assets/9fb1ec2b-5857-4995-9694-f3b1a98bbc04)
la version reste à 1 meme après ctrl+f5 (cache). dans les éléments de l'intégarion , il n'y a rien (pas d'impact).
![image](https://github.com/user-attachments/assets/33bc9861-904b-46ff-a647-717191d32e5b)
bon courage

**Comment by Jezza34000** [comment]
Hello, ok effectivement merci pour ces précieuses informations @Patrick44fr 
Il semble que le client API n'arrive pas à récupérer les données concernant le plan de mensualisation (la prochaine version de l'intégration affichera le montant de la prochaine facture) 
Pouvez-vous me confirmer quand vous vous connecter sur la page principale de eau.veolia.fr
Vous avez bien de noté :
- Mensualisation
- Prélèvement automatique
- Ou si vous avez autre chose pouvez vous me dire quoi ?
Merci pour votre aide

**Comment by Patrick44fr** [comment]
bonjour, je viens de me connecter sur mon compte qui est [https://atlantic-eau.monespace.eau.veolia.fr/mon-espace] et qui fonctionne bien avec la version 1.0.2.
je suis en prélèvement automatique mais par mensualisé.
bonne recherche

**Comment by Patrick44fr** [comment]
s'il faut, je bidouille un peu, je peux envoer le json de mon compte si j'ai les commandes qui vont bien pour interroger l'api veolia

**Comment by Jezza34000** [comment]
D'accord mais du coup vous êtes prélevé chaque mois en consommation réelle ?
Cette information m'intéresse pour finaliser l'intégration de la partie facturation.

Pour ce qui est du bug, il est corrigé dans la dernière version publié, vous pouvez forcer la mise a jour depuis HACS en cliquant sur "Retélécharger".

https://github.com/Jezza34000/home-assistant-veolia/releases/tag/v1.2.3

**Comment by cob94440** [comment]
Bonsoir désolé pour le délai. Pour ma part non ce n'est pas au réel. Suite
au relevé une nouvelle facture est émise et les mensualités suivantes sont
réajustées.

**Comment by Jezza34000** [comment]
Merci pour le retour.
Pouvez-vous me confirmer que la nouvelle version publié corrige le problème ?

**Comment by cob94440** [comment]
Pas pour ma part. Ça a corrigé l'erreur précédente mais nouvelle erreur
Dès que je suis devant le pc je te donne plus d'infos

**Comment by Patrick44fr** [comment]
La nouvelle version est opérationnelle, plus d'erreur 204
Par contre des infos en grisé, mais peut-être est ce normal. Pour la facturation, je suis prélèvement 2 fois par an à 6 mois d'intervalle. 
![Screenshot_2024-11-20-21-31-08-406_io homeassistant companion android](https://github.com/user-attachments/assets/b186ead8-66d6-4860-b736-3f93610936c0)

**Comment by Jezza34000** [comment]
Oui c'est le fonctionnement attendu.
Quand l'alerte logement vide est activé, les alertes journalières et mensuelle ne peuvent etre activés.
Si vous désactiver l'alerte logement vides ces champs là seront alors accessible.

**Comment by cob94440** [comment]
pour ma part voici les erreurs :

`Échec de la configuration, nouvel essai: AlertSettings.__init__() missing 8 required positional arguments: 'daily_enabled', 'daily_threshold', 'daily_notif_email', 'daily_notif_sms', 'monthly_enabled', 'monthly_threshold', 'monthly_notif_email', and 'monthly_notif_sms`

![image](https://github.com/user-attachments/assets/f69713e5-1ef1-4126-a66e-64f4d0bc621e)

Dans les logs 👍
 ```
2024-11-20 22:31:12.345 ERROR (MainThread) [custom_components.veolia] Unexpected error fetching veolia data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/veolia/coordinator.py", line 55, in _async_update_data
    await self.client_api.fetch_all_data(now.year, now.month)
  File "/usr/local/lib/python3.12/site-packages/veolia_api/veolia_api.py", line 519, in fetch_all_data
    self.account_data.alert_settings = await self.get_alerts_settings()
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/veolia_api/veolia_api.py", line 438, in get_alerts_settings
    return AlertSettings()
           ^^^^^^^^^^^^^^^
TypeError: AlertSettings.__init__() missing 8 required positional arguments: 'daily_enabled', 'daily_threshold', 'daily_notif_email', 'daily_notif_sms', 'monthly_enabled', 'monthly_threshold', 'monthly_notif_email', and 'monthly_notif_sms'
```

**Comment by Jezza34000** [comment]
OK je vois le problème. Je corrige ça demain 👍🏻

**Comment by cob94440** [comment]
Super merci de ta réactivité.

**Comment by Jezza34000** [comment]
C'est corrigé
https://github.com/Jezza34000/home-assistant-veolia/releases/tag/v1.2.4

**Comment by Jezza34000** [comment]
Du coup pour comprendre les spécificités qu'il semblent y avoir sur ton interface de gestion peux tu me confirmer : 

- As-tu sur ta page principale l'option pour activer les alertes de consommation mensuelle et journalière ?

Merci

**Comment by cob94440** [comment]
Non je n'ai pas ces paramètres .

**Comment by Jezza34000** [comment]
D'accord l'URL de ton interface de gestion est bien eau.veolia.fr ? Ou c'est une autre

**Comment by cob94440** [comment]
Non c'est bien ça

**Comment by Jezza34000** [comment]
Ok bon il y a des variantes qui ne supportes pas les alertes. Bon à savoir.
Je cloture ce ticket vu que c'est résolu :-)
