### ISSUE TITLE
Installtion

### ISSUE THREAD

**Issue by LGO44** [Jezza34000/home-assistant-veolia#5]
### Détails de la santé du système

Core                               : 2024.11.0.dev0
Interface utilisateur    : 20240930.0

### Checklist

- [X] J'ai activé l'enregistrement des journaux de debug pour mon installation.
- [X] Cette requête ne contient qu'un seul problème (si vous constater plusieurs problèmes, ouvrez un bug pour chaque problème).
- [X] Ce problème n'est pas un doublon de [problèmes précédents](https://github.com/Jezza34000/home-assistant-veolia/issues?q=is%3Aissue+label%3A%22Bug%22+).

### URL du site web de Veolia

https://www.service.eau.veolia.fr/homehttps:///espace-client/votre-consommation.html?vueConso=historique

### Décrire le problème

après installation de l'intégration, sa configuration n'est pas possible 

logs:
2024-11-21 16:04:16.162 INFO (MainThread) [VeoliaAPI] Logging in...
2024-11-21 16:04:16.901 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
![image](https://github.com/user-attachments/assets/3b808b73-0306-4523-8021-5cb3dcf8faa3)

### Étapes de reproduction

1.
2.
3.
...

### Journaux de débogage

```text
2024-11-21 16:04:16.162 INFO (MainThread) [VeoliaAPI] Logging in...
2024-11-21 16:04:16.901 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
```

**Comment by Jezza34000** [comment]
Hello,
C'est noté en gros dans les première lignes : 

UNIQUEMENT compatible avec le nouveau site de Veolia : https://www.eau.veolia.fr/
(N'est pas compatible avec les sites suivant : service.eau.veolia.fr & espace-client.vedif.eau.veolia.fr)

**Comment by LGO44** [comment]
Ok merci pour le retour ultra rapide.
en partant de cette adresse https://www.eau.veolia.fr/ , je rebascule sur l'URL indiquée donc pour moi c'était jouable.

**Comment by LGO44** [comment]
Sur ce site j'avais accès aux nouvelles infos donc j'ai joué...
Désolé pour le dérangement, mais je ne serai pas le seul.
